version: '3.8'
services:
  gocd-server:
    image: gocd/gocd-server:v22.1.0
    container_name: gocd-server
    volumes:
      - gocd-server-data:/godata
      - ./profiles/elastic-agent/config.xml:/tmp/config.xml
      - ./profiles/elastic-agent/elastic-agent.sh:/docker-entrypoint.d/elastic-agent.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AGENT_KEY=${GOCD_AGENT_KEY}
      - GOCD_ADMIN_USER=${GOCD_ADMIN_USER}
      - GOCD_ADMIN_PW=${GOCD_ADMIN_PW}
#      - GO_SERVER_URL=http://10.224.184.256:8153/go
#      - GO_EA_SERVER_URL=http://172.19.0.1:8154/go
      - GOCD_PLUGIN_INSTALL_docker-elastic-agents=https://github.com/gocd-contrib/docker-elastic-agents-plugin/releases/download/v3.2.0-255-exp/docker-elastic-agents-3.2.0-255.jar
      - GOCD_PLUGIN_INSTALL_kubernetes-elastic-agent=https://github.com/gocd/kubernetes-elastic-agents/releases/download/v3.8.2-320/kubernetes-elastic-agent-3.8.2-320.jar
    ports:
      - 8153:8153
      - 8154:8154
    user: root
  #Static agent example
  gocd-static-agent:
    image: gocd/gocd-agent-alpine-3.14:v22.1.0
    container_name: gocd-agent-alpine
    environment:
      - GO_SERVER_URL=http://gocd-server:8153/go
      - AGENT_AUTO_REGISTER_KEY=323040d4-f2e4-4b8a-8394-7a2d122054d1
      - AGENT_AUTO_REGISTER_RESOURCES=Alpine_Static_Agent
    user: root

volumes:
  gocd-server-data:
    driver: local
    #/var/lib/docker/volumes
