version: '2'
services:
  gocd-server:
    image: gocd/gocd-server:v20.3.0
    container_name: gocd-server
    volumes:
      - gocd-server-data:/godata
      - ./profiles/elastic-agent/config.xml:/tmp/config.xml
      - ./profiles/elastic-agent/elastic-agent.sh:/docker-entrypoint.d/elastic-agent.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AGENT_KEY=${GOCD_AGENT_KEY}
      - GOCD_ADMIN_USER=${GOCD_ADMIN_USER}
      - GOCD_ADMIN_PW=${GOCD_ADMIN_PW}
      - GOCD_PLUGIN_INSTALL_docker-elastic-agents=https://github.com/gocd-contrib/docker-elastic-agents-plugin/releases/download/v3.0.0-245/docker-elastic-agents-3.0.0-245.jar
    ports:
      - 8153:8153
      - 8154:8154
  #Static agent example
  gocd-static-agent:
    image: gocd/gocd-agent-alpine-3.9:v20.3.0
    container_name: gocd-agent-alpine
    environment:
      - GO_SERVER_URL=http://gocd-server:8153/go
      - AGENT_AUTO_REGISTER_KEY=323040d4-f2e4-4b8a-8394-7a2d122054d1
      - AGENT_AUTO_REGISTER_RESOURCES=Alpine_Static_Agent

volumes:
  gocd-server-data:
    driver: local
    #/var/lib/docker/volumes
