pipelines:
  cv-static:
    group: Test_Static_Agent
    label_template: "1.0.${COUNT}"
    locking: off
    materials:
      cv:
        git: https://github.com/GaileAlex/cv.git
        branch: master
        destination: ansible-config
    parameters:
      PROJECT_DIR: "/usr/bin/cv"
    stages:
      - build:
          approval: manual
          jobs:
            update-gocd-config:
              profile_id: "Alpine_Static_Agent"
              tasks:
#                - exec:
#                    working_directory: ansible-config
#                    command: bash
#
#                - exec:
#                    working_directory: ansible-config
#                    command:  docker-compose up
                - exec:
                    command: bash
                    working_directory: ansible-config
                    arguments:
                      - -c
                      - echo 'Elastic Agent is start'
                      - docker build -t cv:latest .
                      - echo 'Elastic Agent is working'
                - exec:
                    command: bash
                    working_directory: ansible-config
                    arguments:
                      - "-c"
                      - docker run --rm
                        -v $(pwd)/.secrets:/runner/.secrets
                        -v $(pwd)/README.md:/runner/.secrets/README.md
