pipelines:
  provision-gocd-server-config:
    group: provision
    materials:
      servicegit: # name of material
        git: https://github.com/GaileAlex/GoCd-v2.git
        whitelist:
          - ./pipelines/provision.gocd.yml
        branch: master
        destination: gitmaterialdir
        auto_update: true
    stages:
      - ls_elastic: # name of stage
          clean_workspace: true
          #approval: manual
          jobs: # jobs are ran in parallel
            basic_ls: # name of job
              elastic_profile_id: Alpine_Agent
              tasks:
                - exec:
                    command: bash
                    working_directory: gitmaterialdir
                    arguments:
                      - "-c"
                      - "ls"
      - echo_something: # name of stage
          clean_workspace: true
          #approval: manual
          jobs: # jobs are ran in parallel
            buildjob-docker-image: # name of job
              elastic_profile_id: Alpine_Agent
              tasks:
                - exec:
                    command: bash
                    working_directory: gitmaterialdir
                    arguments:
                      - "-c"
                      - "echo 'Elastic Agent is working'"
                - exec:
                    command: bash
                    working_directory: gitmaterialdir
                    arguments:
                      - "-c"
                      - "pwd"