pipelines:
  provision-gocd-server-config:
    group: provision
    label_template: "1.0.${COUNT}"
    locking: off
    materials:
      poker-ci-provision:
        git: https://github.com/GaileAlex/GoCd-v2.git
        branch: master
        destination: ansible-config
    stages:
      - build:
          jobs:
            any:
              elastic_profile_id: "Alpine_Agent"
              tasks:
                - exec:
                    working_directory: ansible-config
                    command: bash
                - exec:
                    command: bash
                    run_if: failed
                    arguments:
                      - -c
